#!/bin/sh
# SIGHUP'i yoksay (SSH/baslatici kapaninca olmesin - setsid/nohup yok)
trap '' HUP

# Kindle Display Daemon — suspend + RTC wake dongusu (batarya dostu)
# Boot'ta baslar. Her dongude:
#   1) WiFi ac, resmi indir, ekrana yaz, WiFi kapat
#   2) RTC alarmi kur (INTERVAL sn sonra)
#   3) Derin uykuya gir (echo mem)
#   4) RTC uyandirinca basa don
# Cihaz uyandiginda ekranda hep son resim kalir; uyku ekrani basilmaz.

# This file is generated by the server: GET __SERVER__/daemon.sh?dev=__DEV__
DEV="__DEV__"
SERVER="__SERVER__"
IMG_URL="${SERVER}/${DEV}.png"
# Uzaktan komut: admin sayfasina yazilan betik her dongude cekilip bir kez calistirilir
CMD_URL="${SERVER}/cmd.sh?dev=${DEV}"
CMD_STAMP="/mnt/us/.cmd_stamp"
TMP_IMG="/tmp/${DEV}.png"
LOG="/mnt/us/kindle_display.log"
RTC="/sys/class/rtc/rtc1/wakealarm"

EIPS="/usr/sbin/eips"
LIPC="/usr/bin/lipc-set-prop"

INTERVAL=1800      # uyku suresi (sn) = 30 dakika
WIFI_WAIT=8        # WiFi baglanma bekleme
DL_TIMEOUT=25      # indirme icin max sure (sn); Pi agda yoksa/yavassa takilmayi onler

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG"; }

# wget'i zaman sinirli calistir (BusyBox wget --timeout desteklemez).
# Arka planda baslatir, DL_TIMEOUT sn icinde bitmezse oldurur.
wget_timed() {
    OUT="$1"; URL="$2"; LIMIT="$3"
    wget -q -O "$OUT" "$URL" &
    WPID=$!
    i=0
    while [ "$i" -lt "$LIMIT" ]; do
        kill -0 "$WPID" 2>/dev/null || break   # wget bitti
        sleep 1
        i=$((i + 1))
    done
    if kill -0 "$WPID" 2>/dev/null; then
        # Sure doldu, wget hala asili -> oldur
        kill "$WPID" 2>/dev/null
        wait "$WPID" 2>/dev/null
        return 1
    fi
    wait "$WPID" 2>/dev/null
    return $?
}

# Pi'den cmd.sh cek; icerigi oncekinden farkliysa calistir.
# Boyle cihaz uykuda olsa da Pi'ye birakilan komut 1 dongu icinde islenir.
run_remote_cmd() {
    CMD_TMP="/tmp/cmd.sh"
    rm -f "$CMD_TMP"
    wget_timed "$CMD_TMP" "$CMD_URL" 15 || return 0
    [ -s "$CMD_TMP" ] || return 0
    NEW=$(md5sum "$CMD_TMP" 2>/dev/null | cut -d' ' -f1)
    OLD=$(cat "$CMD_STAMP" 2>/dev/null)
    if [ -n "$NEW" ] && [ "$NEW" != "$OLD" ]; then
        log "Yeni cmd.sh bulundu, calistiriliyor"
        echo "$NEW" > "$CMD_STAMP"
        # DEV and SERVER are passed in so commands never hard-code the address
        DEV="$DEV" SERVER="$SERVER" /bin/sh "$CMD_TMP" >> /mnt/us/daemon_debug.log 2>&1
        log "cmd.sh tamamlandi"
    fi
    rm -f "$CMD_TMP"
}

update_screen() {
    $LIPC com.lab126.wifid enable 1 2>/dev/null
    sleep "$WIFI_WAIT"
    rm -f "$TMP_IMG"
    # Pil yuzdesini URL'e ekle ki Pi resme cizebilsin
    BATT=$(/usr/bin/lipc-get-prop com.lab126.powerd battLevel 2>/dev/null)
    [ -z "$BATT" ] && BATT=0
    FULL_URL="${IMG_URL}?batt=${BATT}"
    # En fazla DL_TIMEOUT sn dene; Pi agda yoksa/yavassa takilma
    if wget_timed "$TMP_IMG" "$FULL_URL" "$DL_TIMEOUT" && [ -s "$TMP_IMG" ]; then
        log "Indirildi"
        # WiFi acikken uzaktan komut kontrolu
        run_remote_cmd
        $LIPC com.lab126.wifid enable 0 2>/dev/null
        # Ekrani temizle, e-ink otursun
        $EIPS -c
        sleep 2
        # Tam refresh ile yaz (artifaktsiz)
        $EIPS -f -g "$TMP_IMG"
        # E-ink yazma tamamlansin diye yeterince bekle (suspend oncesi sart!)
        sleep 5
        log "Ekrana yazildi (pil ${BATT})"
        rm -f "$TMP_IMG"
    else
        # Indirme basarisiz/zaman asimi: ekranda son resim kalir, 30dk sonra tekrar denenir
        log "HATA: indirme basarisiz/zaman asimi - son ekran korunuyor"
        $LIPC com.lab126.wifid enable 0 2>/dev/null
        rm -f "$TMP_IMG"
    fi
}

suspend_for() {
    # $1 saniye sonra RTC ile uyan, derin uykuya gir
    echo 0 > "$RTC" 2>/dev/null
    NOW=$(cat /sys/class/rtc/rtc1/since_epoch)
    echo $((NOW + $1)) > "$RTC" 2>/dev/null
    sync
    log "Suspend (${1}sn RTC alarm)"
    BEFORE=$(cat /sys/class/rtc/rtc1/since_epoch)
    echo mem > /sys/power/state
    AFTER=$(cat /sys/class/rtc/rtc1/since_epoch)
    SLEPT=$((AFTER - BEFORE))
    log "Resume (uyku ${SLEPT}sn)"
    # Suspend basarisiz olduysa (cok kisa surdu) pili korumak icin normal sleep
    if [ "$SLEPT" -lt 5 ]; then
        log "UYARI: suspend basarisiz, sleep ile bekleniyor"
        sleep "$1"
    fi
}

# Tek instance garantisi: PID dosyasi
PIDFILE="/tmp/kindle_daemon.pid"
if [ -f "$PIDFILE" ]; then
    OLD=$(cat "$PIDFILE" 2>/dev/null)
    if [ -n "$OLD" ] && kill -0 "$OLD" 2>/dev/null; then
        log "Daemon zaten calisiyor (PID=$OLD), cikiliyor"
        exit 0
    fi
fi
echo $$ > "$PIDFILE"
trap 'rm -f "$PIDFILE"' EXIT

log "=== Daemon basladi (PID=$$) ==="
# Kindle UI'nin kendi screensaver/suspend'ini engelle, kontrolu biz alalim
$LIPC com.lab126.powerd preventScreenSaver 1 2>/dev/null

# Ilk dongu: resmi cizip dogrudan uyku dongusune gir (mudahale penceresi yok).
# Bakim gerekirse cihazi reboot edip watchdog penceresinde mudahale edilir.
while true; do
    update_screen
    suspend_for "$INTERVAL"
    # Resume sonrasi kisa bekleme (sistemin oturmasi icin)
    sleep 3
done
